version: '3.8'

services:
  gateway-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - JWT_SECRET=dev-secret-key-32-chars-minimum-required
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    volumes:
      - ..:/app
      - /app/bin  # Exclude bin directory
    networks:
      - gateway-network
    command: air -c .air.toml

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge