# Production Configuration for Kalshi API Gateway
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

auth:
  jwt:
    secret: "your-secret-key-change-this-in-production-must-be-32-chars"
    access_expiry: "24h"
    refresh_expiry: "168h"
  api_key:
    enabled: true
    header: "X-API-Key"

rate_limit:
  default_rate: 1000        # requests per minute
  burst_capacity: 100
  storage: "redis"
  cleanup_interval: "60s"

cache:
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    ttl: "300s"
  memory:
    max_size: 1000
    ttl: "60s"

circuit:
  failure_threshold: 5
  recovery_timeout: "30s"
  max_requests: 3

backends:
  - name: "httpbin"
    url: "https://httpbin.org"
    health_check: "/status/200"
    weight: 100
  - name: "jsonplaceholder"
    url: "https://jsonplaceholder.typicode.com"
    health_check: "/posts/1"
    weight: 100

routes:
  - path: "/api/test/*"
    backend: "httpbin"
    methods: ["GET", "POST"]
    rate_limit: 500
    cache_ttl: "120s"
  - path: "/api/posts/*"
    backend: "jsonplaceholder"
    methods: ["GET"]
    rate_limit: 1000
    cache_ttl: "300s"

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  path: "/metrics"
  port: 9090