# Test Configuration - Minimal setup for testing
server:
  port: 8081
  host: "localhost"
  read_timeout: "5s"
  write_timeout: "5s"
  idle_timeout: "10s"

auth:
  jwt:
    secret: "test-secret-key-32-chars-minimum-required"
    access_expiry: "1h"
    refresh_expiry: "24h"
  api_key:
    enabled: true
    header: "X-API-Key"

rate_limit:
  default_rate: 1000
  burst_capacity: 100
  storage: "memory"
  cleanup_interval: "10s"

cache:
  memory:
    max_size: 50
    ttl: "10s"

circuit:
  failure_threshold: 2
  recovery_timeout: "5s"
  max_requests: 1

backends:
  - name: "test-backend"
    url: "http://localhost:8082"
    health_check: "/health"
    weight: 100

routes:
  - path: "/api/test/*"
    backend: "test-backend"
    methods: ["GET", "POST", "PUT", "DELETE"]
    rate_limit: 100
    cache_ttl: "10s"

logging:
  level: "error"
  format: "text"

metrics:
  enabled: false