server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

auth:
  jwt:
    secret: "your-secret-key-change-this-in-production"
    expiry: "24h"
  api_key:
    enabled: true
    header: "X-API-Key"

rate_limit:
  default_rate: 1000
  burst_capacity: 100
  storage: "memory"
  cleanup_interval: "60s"

cache:
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    ttl: "300s"
  memory:
    max_size: 1000
    ttl: "60s"

circuit:
  failure_threshold: 5
  recovery_timeout: "30s"
  max_requests: 3

backend:
  - name: "service1"
    url: "http://localhost:3000"
    health_check: "/health"
    weight: 100

routes:
  - path: "/api/v1/*"
    backend: "service1"
    methods: ["GET", "POST", "PUT", "DELETE"]
    rate_limit: 500
    cache_ttl: "120s"

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  path: "/metrics"
  port: 9090